[project]
name = "DDT"
version = "2.0"
description = "Shearer data download tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "bokeh>=3.7.3",
    "customtkinter>=5.2.2",
    "lz4>=4.4.4",
    "pillow>=11.3.0",
]
