"""IO point mappings and VFD configurations"""

# All IO points
IO_POINTS = {
    "LPumpPhaseA": {"type": "", "readable_name": "LH Pump Current (A)"},
    "LPumpPhaseB": {"type": "", "readable_name": "LH Pump Current (B)"},
    "LPumpPhaseC": {"type": "", "readable_name": "LH Pump Current (C)"},
    "RPumpPhaseA": {"type": "", "readable_name": "RH Pump Current (A)"},
    "RPumpPhaseB": {"type": "", "readable_name": "RH Pump Current (B)"},
    "RPumpPhaseC": {"type": "", "readable_name": "RH Pump Current (C)"},
    "LCutterPhaseA": {"type": "", "readable_name": "LH Cutter Current (A)"},
    "LCutterPhaseB": {"type": "", "readable_name": "LH Cutter Current (B)"},
    "LCutterPhaseC": {"type": "", "readable_name": "LH Cutter Current (C)"},
    "RCutterPhaseA": {"type": "", "readable_name": "RH Cutter Current (A)"},
    "RCutterPhaseB": {"type": "", "readable_name": "RH Cutter Current (B)"},
    "RCutterPhaseC": {"type": "", "readable_name": "RH Cutter Current (C)"},
    "LTramPhaseA": {"type": "", "readable_name": "LH Haulage Current (A)"},
    "LTramPhaseB": {"type": "", "readable_name": "LH Haulage Current (B)"},
    "LTramPhaseC": {"type": "", "readable_name": "LH Haulage Current (C)"},
    "RTramPhaseA": {"type": "", "readable_name": "RH Haulage Current (A)"},
    "RTramPhaseB": {"type": "", "readable_name": "RH Haulage Current (B)"},
    "RTramPhaseC": {"type": "", "readable_name": "RH Haulage Current (C)"},
    "LumpBkrPhaseA": {"type": "", "readable_name": "Lumpbreaker Current (A)"},
    "LumpBkrPhaseB": {"type": "", "readable_name": "Lumpbreaker Current (B)"},
    "LumpBkrPhaseC": {"type": "", "readable_name": "Lumpbreaker Current (C)"},
    "LPumpRTD": {"type": "", "readable_name": "LH Pump Temp"},
    "RPumpRTD": {"type": "", "readable_name": "RH Pump Temp"},
    "LCutterRTD": {"type": "", "readable_name": "LH Cutter Temp"},
    "RCutterRTD": {"type": "", "readable_name": "RH Cutter Temp"},
    "LTramRTD": {"type": "", "readable_name": "LH Haulage Temp"},
    "RTramRTD": {"type": "", "readable_name": "RH Haulage Temp"},
    "LumpBkrRTD": {"type": "", "readable_name": "Lumpbreaker Temp"},
    "ControllerRTD": {"type": "", "readable_name": "Controller Temp"},
    "LineVoltageA": {"type": "", "readable_name": "Line Voltage (A)"},
    "LineVoltageB": {"type": "", "readable_name": "Line Voltage (B)"},
    "LineVoltageC": {"type": "", "readable_name": "Line Voltage (C)"},
    "LineCurrentA": {"type": "", "readable_name": "Line Current (A)"},
    "LineCurrentB": {"type": "", "readable_name": "Line Current (B)"},
    "LineCurrentC": {"type": "", "readable_name": "Line Current (C)"},
    "ControlVoltage": {"type": "", "readable_name": "Control Voltage"},
    "VFDActSpeed": {"type": "", "readable_name": "Actual Speed"},
    "VFDDesSpeed": {"type": "", "readable_name": "Desired Speed"},
    "lHydraulicPress": {"type": "", "readable_name": "LH Hydraulic Pressure"},
    "rHydraulicPress": {"type": "", "readable_name": "RH Hydraulic Pressure"},
    "lDrumH2OFlow": {"type": "", "readable_name": "LH Drum H2O Flow"},
    "rDrumH2OFlow": {"type": "", "readable_name": "RH Drum H2O Flow"},
    "lCutterH2OFlow": {"type": "", "readable_name": "LH Cutter H2O Flow"},
    "rCutterH2OFlow": {"type": "", "readable_name": "RH Cutter H2O Flow"},
    "lDrumH2OPress": {"type": "", "readable_name": "LH Drum H2O Pressure"},
    "rDrumH2OPress": {"type": "", "readable_name": "RH Drum H2O Pressure"},
    "lCutterH2OPress": {"type": "", "readable_name": "LH Cutter H2O Pressure"},
    "rCutterH2OPress": {"type": "", "readable_name": "RH Cutter H2O Pressure"},
    "LeftVFDTemp": {"type": "", "readable_name": "LH VFD Temp"},
    "RightVFDTemp": {"type": "", "readable_name": "RH VFD Temp"},
    "BussSupplyTemp": {"type": "", "readable_name": "Bus Supply Temp"},
    "LeftBusVoltage": {"type": "", "readable_name": "LH Bus Volts"},
    "RightBusVoltage": {"type": "", "readable_name": "RH Bus Volts"},
    "rRangingarmTemp": {"type": "", "readable_name": "RH Arm Temp"},
    "lRangingarmTemp": {"type": "", "readable_name": "LH Arm Temp"},
    "lTramOilTemp": {"type": "", "readable_name": "LH Tram Oil Temp"},
    "rTramOilTemp": {"type": "", "readable_name": "RH Tram Oil Temp"},
    "lHaulBearingRTD": {"type": "", "readable_name": "LH  Bearing Temp"},
    "rHaulBearingRTD": {"type": "", "readable_name": "RH  Bearing Temp"},
    "HaulDir": {"type": "", "readable_name": "Haulage Direction"},
    "SupportNo": {"type": "", "readable_name": "Support Number"},
    "MetersToHeadSIRSA": {"type": "", "readable_name": "Meters to MG"},
    "HaulageWtrFlw1": {"type": "", "readable_name": "Haulage H2O Flow 1"},
    "HaulageWtrFlw2": {"type": "", "readable_name": "Haulage H2O Flow 2"},
    "HaulageWtrPres1": {"type": "", "readable_name": "Haulage H2O Pressure 1"},
    "HaulageWtrPres2": {"type": "", "readable_name": "Haulage H2O Pressure 2"},
    "MMX01": {"type": "devOk", "readable_name": "MMX Comms "},
    "LPUMPMCT": {"type": "devOk", "readable_name": "LH Pump MCT Comms"},
    "RPUMPMCT": {"type": "devOk", "readable_name": "RH Pump MCT Comms"},
    "LCUTMCT": {"type": "devOk", "readable_name": "LH Cutter MCT Comms"},
    "RCUTMCT": {"type": "devOk", "readable_name": "RH Cutter MCT Comms"},
    "LBKRMCT": {"type": "devOk", "readable_name": "Lump MCT Comms"},
    "XFMRMCT": {"type": "devOk", "readable_name": "Xfmr MCT Comms"},
    "ESX3XM01": {"type": "devOk", "readable_name": "3XM1 Comms"},
    "ESX3XM02": {"type": "devOk", "readable_name": "3XM2 Comms"},
    "ESX3XM03": {"type": "", "readable_name": "ESX3XM03"},
    "ESX3XM04": {"type": "", "readable_name": "ESX3XM04"},
    "LBOOMINC": {"type": "devOk", "readable_name": "LH Incimometer Comms"},
    "RBOOMINC": {"type": "devOk", "readable_name": "RH Incimometer Comms"},
    "LUMPINC": {"type": "devOk", "readable_name": "Lump Inclinometer Comms"},
    "PITCHROLLINC": {"type": "devOk", "readable_name": "Pitch and Roll Comms"},
    "REGEN_VFD": {"type": "devOk", "readable_name": "Regen Comms"},
    "lHaulAbsEnc": {"type": "devOk", "readable_name": "LH Haul Encoder Comms"},
    "rHaulAbsEnc": {"type": "devOk", "readable_name": "RH Haul Encoder Comms"},
    "lRaAbsEnc": {"type": "devOk", "readable_name": "LH Arm Encoder Comms"},
    "rRaAbsEnc": {"type": "devOk", "readable_name": "RH Arm Encoder Comms"},
    "lCowlAbsEnc": {"type": "devOk", "readable_name": "LH Cowl Encoder Comms"},
    "rCowlAbsEnc": {"type": "devOk", "readable_name": "RH Cowl Encoder Comms"},
    "RH_GIO_1": {"type": "devOk", "readable_name": "RH GIO 1 Comms"},
    "RH_GIO_2": {"type": "devOk", "readable_name": "RH GIO 2 Comms"},
    "LH_GIO_1": {"type": "devOk", "readable_name": "LH GIO 1 Comms"},
    "LH_GIO_2": {"type": "devOk", "readable_name": "LH GIO 2 Comms"},
    "Mcut_LShoeHt": {"type": "", "readable_name": "Mcut_LShoeHt"},
    "Mcut_RShoeHt": {"type": "", "readable_name": "Mcut_RShoeHt"},
    "ShrStepNo": {"type": "", "readable_name": "ASA Step Number"},
    "ASA_BmMethAndMode_L": {"type": "", "readable_name": "LH Boom Mode"},
    "ASA_BmMethAndMode_R": {"type": "", "readable_name": "RH Boom Mode"},
    "Mcut_RollAngle": {"type": "", "readable_name": "Roll Angle"},
    "Mcut_PitchAngle": {"type": "", "readable_name": "Pitch Angle"},
    "Mcut_PrevPitch": {"type": "", "readable_name": "Previous Pitch Angle"},
    "Mcut_LBoomAng": {"type": "", "readable_name": "LH Boom Angle"},
    "Mcut_RBoomAng": {"type": "", "readable_name": "RH Boom Angle"},
    "Mcut_LRelBmHt": {"type": "", "readable_name": "LH Actual  Height"},
    "Mcut_RRelBmHt": {"type": "", "readable_name": "RH Actual  Height"},
    "Mcut_LRefBmHt": {"type": "", "readable_name": "LH Desired Height"},
    "Mcut_RRefBmHt": {"type": "", "readable_name": "RH Desired Height"},
    "TopPickHt_L": {"type": "", "readable_name": "LH Top Pick Height"},
    "TopPickHt_R": {"type": "", "readable_name": "RH Top Pick Height"},
    "BottomPickHt_L": {"type": "", "readable_name": "LH Bottom Pick Height"},
    "BottomPickHt_R": {"type": "", "readable_name": "RH Bottom Pick Height"},
    "Mcut_DesExt": {"type": "", "readable_name": "Desired Extraction"},
    "Mcut_ActExt": {"type": "", "readable_name": "Actual Extraction"},
    "asaMode": {"type": "", "readable_name": "ASA Mode"},
    "Mcut_PitchHt_L": {"type": "", "readable_name": "LH Pitch Comp"},
    "Mcut_PitchHt_R": {"type": "", "readable_name": "RH Pitch Comp"},
    "ActualCutPitchCorr": {"type": "", "readable_name": "Actual Cut PIT Correction"},
    "CalculatedPitchCorr": {"type": "", "readable_name": "Calculated PIT Correction"},
    "RoofCutPIT": {"type": "", "readable_name": "RRF PIT Roof Drum Status "},
    "SupportNo_LH": {"type": "", "readable_name": "LH Support Number"},
    "SupportNo_RH": {"type": "", "readable_name": "RH Support Number"},
    "lOilTemp": {"type": "", "readable_name": "LH Oil Temp"},
    "rOilTemp": {"type": "", "readable_name": "RH Oil Temp"},
    "lAux1Temp": {"type": "", "readable_name": "LH Aux 1 Temp"},
    "lAux2Temp": {"type": "", "readable_name": "LH Aux 2 Temp"},
    "rAux1Temp": {"type": "", "readable_name": "RH Aux 1 Temp"},
    "rAux2Temp": {"type": "", "readable_name": "RH Aux 2 Temp"},
    "TrlCblStrnGauge": {"type": "", "readable_name": "Strain Gauge"},
    "lHydraulicFlow": {"type": "", "readable_name": "LH Hydraulic Flow"},
    "rHydraulicFlow": {"type": "", "readable_name": "RH Hydraulic Flow"},
    "HaulageXfmrRTD": {"type": "", "readable_name": "Haulage Transformer Temp"},
    "lCoolingWtrTemp": {"type": "", "readable_name": "LH Cooling Water Temp"},
    "rCoolingWtrTemp": {"type": "", "readable_name": "RH Cooling Water Temp"},
    "waterPress1": {"type": "", "readable_name": "Water Pressure 1"},
    "waterPress2": {"type": "", "readable_name": "Water Pressure 2"},
    "waterFlow1": {"type": "", "readable_name": "Water Flow 1"},
    "waterFlow2": {"type": "", "readable_name": "Water Flow 2"},
    "lHydraulicPressDiff": {"type": "", "readable_name": "LH Hyd Press Differential"},
    "rHydraulicPressDiff": {"type": "", "readable_name": "RH Hyd Press Differential"},
}

# Vfd points (reversed mapping because of duplicate key)
VFD_POINTS = {
    "LH VFD Link Volts": {"type": "link_volts", "name": "LEFT_VFD"},
    "RH VFD Link Volts": {"type": "link_volts", "name": "RIGHT_VFD"},
    "LH VFD Motor Volts": {"type": "motor_volt", "name": "LEFT_VFD"},
    "RH VFD Motor Volts": {"type": "motor_volt", "name": "RIGHT_VFD"},
    "LH VFD Ref Freq": {"type": "frequency_ref", "name": "LEFT_VFD"},
    "RH VFD Ref Freq": {"type": "frequency_ref", "name": "RIGHT_VFD"},
    "LH VFD Actual Freq": {"type": "frequency_actual", "name": "LEFT_VFD"},
    "RH VFD Actual Freq": {"type": "frequency_actual", "name": "RIGHT_VFD"},
    "LH VFD Comms": {"type": "devok", "name": "LEFT_VFD"},
    "RH VFD Comms": {"type": "devok", "name": "RIGHT_VFD"},
}

# IO types
IO_TYPES = {
    "J_DI_TYPE": "DigitalInput@0",
    "J_DO_TYPE": "DigitalOutput@0",
    "J_AI_TYPE": "AnalogInput@0",
    "J_LI_TYPE": "LongInput@0",
    "J_LO_TYPE": "LongOutput@0",
    "J_SI_TYPE": "ShortInput@0",
    "J_SO_TYPE": "ShortOutput@0",
    "J_PVI_TYPE": "PropVInput@0",
    "J_PVO_TYPE": "PropVOutput@0",
    "J_NDSTAT_TYPE": "NodeStatus@0",
}

# Graph presets
GRAPH_PRESETS = {
    "Control Voltage": ["ControlVoltage"],
    "Bus Voltage": ["LH VFD Link Volts", "RH VFD Link Volts"],
    "Pump Amps": [
        "LPumpPhaseA",
        "LPumpPhaseB",
        "LPumpPhaseC",
        "RPumpPhaseA",
        "RPumpPhaseB",
        "RPumpPhaseC",
    ],
    "Lumpbreaker Amps": ["LumpBkrPhaseA", "LumpBkrPhaseB", "LumpBkrPhaseC"],
    "Haulage Amps": [
        "LTramPhaseA",
        "LTramPhaseB",
        "LTramPhaseC",
        "RTramPhaseA",
        "RTramPhaseB",
        "RTramPhaseC",
    ],
    "Cutter Amps": [
        "LCutterPhaseA",
        "LCutterPhaseB",
        "LCutterPhaseC",
        "RCutterPhaseA",
        "RCutterPhaseB",
        "RCutterPhaseC",
    ],
    "Controller Temps": ["ControllerRTD"],
    "Hydraulic Flow & Pressure": [
        "rHydraulicPress",
        "lHydraulicPress",
        "lHydraulicFlow",
        "rHydraulicFlow",
    ],
    "Auxilary Temps": ["lAux1Temp", "lAux2Temp", "rAux1Temp", "rAux2Temp"],
    "Machine Position": ["SupportNo_LH", "SupportNo_RH", "SupportNo"],
    "Drum Water Flow & Pressure": [
        "lDrumH2OFlow",
        "rDrumH2OFlow",
        "lDrumH2OPress",
        "rDrumH2OPress",
    ],
    "Line Voltage": ["LineVoltageA", "LineVoltageB", "LineVoltageC"],
    "Haulage Voltage": ["LH VFD Motor Volts", "RH VFD Motor Volts"],
    "Pump Temp": ["LPumpRTD", "RPumpRTD"],
    "Lumpbreaker Temp": ["LumpBkrRTD"],
    "Haulage Temp": ["LTramRTD", "RTramRTD"],
    "Cutter Temp": ["LCutterRTD", "RCutterRTD"],
    "Arm Bearing Temp": ["lRangingarmTemp", "rRangingarmTemp"],
    "Trail Cable Strain Guage": ["TrlCblStrnGauge"],
    "Hyd Oil Temp": ["lOilTemp", "rOilTemp"],
    "Haulage Speeds": ["VFDDesSpeed", "VFDActSpeed"],
    "Currents & Speeds": [
        "LTramPhaseA",
        "LTramPhaseB",
        "LTramPhaseC",
        "RTramPhaseA",
        "RTramPhaseB",
        "RTramPhaseC",
        "LCutterPhaseA",
        "LCutterPhaseB",
        "LCutterPhaseC",
        "RCutterPhaseA",
        "RCutterPhaseB",
        "RCutterPhaseC",
        "VFDDesSpeed",
        "VFDActSpeed",
    ],
}
